### ISSUE TITLE
Unable to edit bigger STORE file

### ISSUE THREAD

**Issue by rlukacik** [cschuller/yak-js#41]
When try to open the *.txt file in STORE section via YAKjs, the browser will freeze.
Attached is file for testing.
[channel-config.txt](https://github.com/cschuller/yak-js/files/63902/channel-config.txt)

**Comment by dasMulli** [comment]
Works fine on my machines (os x 10.11: safari / chrome, windows 10: chrome 32bit / chrome 64bit / IE 11 / Edge). Scrolling lags a bit when running the 32bit chrome on windows, IE/Edge both scroll smoothly but doesn't immediately render lines coming into the screen.

**Comment by cschuller** [comment]
Works fine on my machine (windows 10: chrome 64 bit 47.x, firefox 42.x, edge) Scrolling lags on firefox.

Can your provide more information, OS, Browser vendor, version?

**Comment by cschuller** [comment]
Issue could not be reproduced and more information missing.
